version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  broker:
    image: confluentinc/cp-kafka:6.2.0
    container_name: broker
    ports:
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  db:
    image: postgres
    container_name: kafka-db
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: .543uwuowo123uwuowo543.
      POSTGRES_DB: earthquakes

  producer:
    build: ./javascript
    image: kafka/producer
    container_name: kafka-javascript-producer
    depends_on:
      - broker


  consumer:
    build: ./KafkaConsumer
    image: kafka/consumer
    container_name: kafka-java-consumer
    ports:
      - 8081:8081
    depends_on:
      - db
      - broker

  frontend:
    build: ./front
    image: kafka/front
    container_name: kafka-frontend
    ports:
      - 8082:8082
    depends_on:
      - consumer
